"""
OptiS Benchmark - Report Generator Tests

Tests for ReportGenerator.
"""

import pytest
from src.core.evaluator import ReportGenerator, EvaluationResult


class TestReportGenerator:
    """Tests for ReportGenerator."""

    def test_generate_html_report(self, sample_results: list[EvaluationResult]):
        """Test HTML report generation."""
        html = ReportGenerator.generate_html_report(
            results=sample_results,
            model_name="GPT-4",
            task_name="Lens Design",
        )

        # Check basic structure
        assert "<!DOCTYPE html>" in html
        assert "OptiS Benchmark Report" in html
        assert "GPT-4" in html
        assert "Lens Design" in html

        # Check CSS is present
        assert "<style>" in html
        assert ".stat-card" in html

        # Check statistics are rendered
        assert "Success Rate" in html
        assert "Avg Score" in html
        assert "Avg Latency" in html

    def test_generate_html_report_with_percentages(self, sample_results: list[EvaluationResult]):
        """Test HTML report contains percentage values."""
        html = ReportGenerator.generate_html_report(
            results=sample_results,
            model_name="Claude-3",
            task_name="Paper Review",
        )

        # Should contain percentage format (e.g., "75.0%")
        assert "%" in html

    def test_generate_html_report_error_summary(self, sample_results: list[EvaluationResult]):
        """Test HTML report includes error summary."""
        html = ReportGenerator.generate_html_report(
            results=sample_results,
            model_name="Gemini",
            task_name="Retrieval",
        )

        # Should include error categories
        assert "Success" in html
        assert "Timeout" in html or "API Error" in html

    def test_generate_markdown_report(self, sample_results: list[EvaluationResult]):
        """Test Markdown report generation."""
        md = ReportGenerator.generate_markdown_report(
            results=sample_results,
            model_name="GPT-4",
            task_name="Summarization",
        )

        # Check basic structure
        assert "# OptiS Benchmark Report" in md
        assert "## Overview" in md
        assert "## Summary" in md
        assert "## Score Distribution" in md
        assert "## Error Summary" in md

        # Check values are present
        assert "GPT-4" in md
        assert "Summarization" in md

    def test_markdown_report_contains_tables(self, sample_results: list[EvaluationResult]):
        """Test Markdown report contains proper tables."""
        md = ReportGenerator.generate_markdown_report(
            results=sample_results,
            model_name="Test Model",
            task_name="Test Task",
        )

        # Markdown tables use | delimiter
        assert "|" in md
        assert "---" in md  # Table separator

    def test_markdown_report_contains_metrics(self, sample_results: list[EvaluationResult]):
        """Test Markdown report contains all expected metrics."""
        md = ReportGenerator.generate_markdown_report(
            results=sample_results,
            model_name="Test",
            task_name="Test",
        )

        # Should contain key metrics
        assert "Total Tasks" in md
        assert "Success Rate" in md
        assert "Average Score" in md
        assert "Composite Score" in md

    def test_html_report_timestamp(self, sample_results: list[EvaluationResult]):
        """Test HTML report contains timestamp."""
        import re

        html = ReportGenerator.generate_html_report(
            results=sample_results,
            model_name="Test",
            task_name="Test",
        )

        # Should match format like "2024-01-15 10:30:00"
        timestamp_pattern = r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"
        assert re.search(timestamp_pattern, html)

    def test_markdown_report_footer(self, sample_results: list[EvaluationResult]):
        """Test Markdown report contains footer."""
        md = ReportGenerator.generate_markdown_report(
            results=sample_results,
            model_name="Test",
            task_name="Test",
        )

        assert "Report generated by OptiS Benchmark" in md

    def test_report_with_all_successes(self):
        """Test report generation with all successful results."""
        results = [
            EvaluationResult(
                task_id=f"task_{i}",
                success=True,
                score=0.9 + i * 0.01,
                execution_time=10.0,
                cost=0.05,
            )
            for i in range(5)
        ]

        html = ReportGenerator.generate_html_report(results, "Model", "Task")
        md = ReportGenerator.generate_markdown_report(results, "Model", "Task")

        assert "100.0%" in html  # 100% success rate
        assert "5" in md  # 5 tasks

    def test_report_with_all_failures(self):
        """Test report generation with all failed results."""
        results = [
            EvaluationResult(
                task_id=f"task_{i}",
                success=False,
                score=0.1 * i,
                error="Test error",
                execution_time=10.0,
                cost=0.05,
            )
            for i in range(3)
        ]

        html = ReportGenerator.generate_html_report(results, "Model", "Task")
        md = ReportGenerator.generate_markdown_report(results, "Model", "Task")

        assert "0.0%" in html or "0%" in html  # 0% success rate
        assert "0" in md

    def test_report_with_various_errors(self):
        """Test report with various error types."""
        results = [
            EvaluationResult(
                task_id="1",
                success=False,
                score=0.0,
                error="Timeout",
                execution_time=300.0,
            ),
            EvaluationResult(
                task_id="2",
                success=False,
                score=0.0,
                error="API rate limit",
                execution_time=5.0,
            ),
            EvaluationResult(
                task_id="3",
                success=False,
                score=0.0,
                error="Invalid output format",
                execution_time=10.0,
            ),
            EvaluationResult(
                task_id="4",
                success=True,
                score=0.85,
                execution_time=12.0,
            ),
        ]

        html = ReportGenerator.generate_html_report(results, "Model", "Task")

        # All error categories should appear
        assert "Timeout" in html or "timeout" in html.lower()
        assert "Error" in html

    def test_html_report_responsive_design(self, sample_results: list[EvaluationResult]):
        """Test HTML report has responsive design elements."""
        html = ReportGenerator.generate_html_report(
            results=sample_results,
            model_name="Test",
            task_name="Test",
        )

        # Check for responsive CSS
        assert "max-width" in html
        assert "grid" in html or "flex" in html

    def test_report_generation_empty_results(self):
        """Test report generation with empty results list."""
        html = ReportGenerator.generate_html_report([], "Model", "Task")
        md = ReportGenerator.generate_markdown_report([], "Model", "Task")

        # Should still generate valid HTML/MD
        assert "<!DOCTYPE html>" in html
        assert "# OptiS Benchmark Report" in md

        # But metrics should be zero/invalid
        assert "0" in html or "NaN" in html or "undefined" in html.lower()

    def test_markdown_report_numeric_formatting(self, sample_results: list[EvaluationResult]):
        """Test that numeric values are properly formatted in markdown."""
        md = ReportGenerator.generate_markdown_report(
            results=sample_results,
            model_name="Test",
            task_name="Test",
        )

        # Check for formatted numbers (should have decimal points)
        import re

        decimal_pattern = r"\d+\.\d+"
        assert re.search(decimal_pattern, md)
