"""
OptiS Benchmark — Markdown Report Builder

A reusable builder class for assembling Markdown documents programmatically.

Key features:

* **Fluent API** — most methods return ``self`` for method chaining.
* **i18n support** — ``lang="zh_CN"`` switches built-in section labels.
* **Mermaid helpers** — ``mermaid_bar``, ``mermaid_pie`` for common chart types.
* **Typing-first** — full type hints.

Usage::

    builder = MdReportBuilder(lang="zh_CN")
    report = (
        builder
        .h1("Title")
        .p("Some text")
        .table(["Col1", "Col2"], [["A", "1"], ["B", "2"]])
        .mermaid_bar("My Chart", ["A", "B"], [3.0, 4.5])
        .build()
    )
"""

from __future__ import annotations

from typing import Any


# ======================================================================
# i18n translation tables
# ======================================================================

I18N: dict[str, dict[str, str]] = {
    "en": {
        "report_title": "Paper Evaluation Report",
        "generated": "Generated",
        "commit": "Commit",
        "source": "Source",
        "duration": "Duration",
        "offline_warning": (
            "**⚠️ Offline mode** \u2014 all scores are 0.0 because no LLM judge "
            "was configured. Run with ``--online`` to use the vLLM endpoint for "
            "real LLM-based scoring."
        ),
        "paper_meta": "Paper Meta Information",
        "field": "Field",
        "value": "Value",
        "eval_metrics": "Evaluation Metrics Summary",
        "metric": "Metric",
        "score": "Score (1-5)",
        "hallucination_rate": "Hallucination Rate",
        "visual_summary": "Visual Summary",
        "rubric_scores_chart": "Rubric Scores (1-5)",
        "figure_prefix": "Figure",
        "per_field": "Per-Field",
        "hallucination_chart": "Hallucination Breakdown",
        "hallucinated": "Hallucinated",
        "valid": "Valid",
        "hallucinated_vs_valid": "Hallucinated vs valid items",
        "per_field_detail": "Per-Field Detail",
        "dimension": "Dimension",
        "justification": "Justification",
        "hallucinated_items": "Hallucinated Items",
        "content": "Content",
        "raw_metrics": "Raw Metrics",
        "footer_generated_by": (
            "Report generated by "
            "[OptiS Benchmark](https://github.com/ywzhang909/OpticsBenchmark) "
            "RubricBasedEvaluator"
        ),
        "scores_all_zero": "Scores",
        "items": "items",
        "accuracy": "Accuracy",
        "completeness": "Completeness",
        "readability": "Readability",
    },
    "zh_CN": {
        "report_title": "\u8bba\u6587\u8bc4\u4f30\u62a5\u544a",
        "generated": "\u751f\u6210\u65f6\u95f4",
        "commit": "\u63d0\u4ea4\u54c8\u5e0c",
        "source": "\u6e90\u6587\u4ef6",
        "duration": "\u8017\u65f6",
        "offline_warning": (
            "**\u26a0\ufe0f \u79bb\u7ebf\u6a21\u5f0f** \u2014 "
            "\u6240\u6709\u5f97\u5206\u5747\u4e3a 0.0\uff0c\u56e0\u4e3a\u672a\u914d\u7f6e LLM "
            "\u8bc4\u5ba1\u5668\u3002\u8bf7\u4f7f\u7528 ``--online`` \u53c2\u6570\u542f\u7528 "
            "vLLM \u7aef\u70b9\u83b7\u53d6\u5b9e\u9645\u8bc4\u5206\u3002"
        ),
        "paper_meta": "\u8bba\u6587\u5143\u4fe1\u606f",
        "field": "\u5b57\u6bb5",
        "value": "\u503c",
        "eval_metrics": "\u8bc4\u4f30\u6307\u6807\u6c47\u603b",
        "metric": "\u6307\u6807",
        "score": "\u5f97\u5206 (1-5)",
        "hallucination_rate": "\u5e7b\u89c9\u7387",
        "visual_summary": "\u53ef\u89c6\u5316\u6c47\u603b",
        "rubric_scores_chart": "\u8bc4\u5206\u6982\u89c8 (1-5)",
        "figure_prefix": "\u56fe",
        "per_field": "\u6bcf\u5b57\u6bb5",
        "hallucination_chart": "\u5e7b\u89c9\u5206\u5e03",
        "hallucinated": "\u5e7b\u89c9",
        "valid": "\u6709\u6548",
        "hallucinated_vs_valid": "\u5e7b\u89c9\u4e0e\u6709\u6548\u9879\u76ee\u5bf9\u6bd4",
        "per_field_detail": "\u5404\u5b57\u6bb5\u8be6\u60c5",
        "dimension": "\u7ef4\u5ea6",
        "justification": "\u8bf4\u660e",
        "hallucinated_items": "\u5e7b\u89c9\u9879\u76ee",
        "content": "\u5185\u5bb9",
        "raw_metrics": "\u539f\u59cb\u6307\u6807",
        "footer_generated_by": (
            "\u672c\u62a5\u544a\u7531 "
            "[OptiS Benchmark](https://github.com/ywzhang909/OpticsBenchmark) "
            "RubricBasedEvaluator \u81ea\u52a8\u751f\u6210"
        ),
        "scores_all_zero": "\u5f97\u5206",
        "items": "\u9879",
        "accuracy": "\u51c6\u786e\u5ea6",
        "completeness": "\u5b8c\u6574\u5ea6",
        "readability": "\u53ef\u8bfb\u6027",
    },
}


# ======================================================================
# Builder
# ======================================================================


class MdReportBuilder:
    """A fluent Markdown document builder.

    Args:
        lang: Language code (``"en"`` or ``"zh_CN"``).

    Usage::

        md = MdReportBuilder(lang="zh_CN")
        md.h1("Title")
        md.p("Body text")
        md.table(["A", "B"], [["1", "2"], ["3", "4"]])
        print(md.build())
    """

    def __init__(self, lang: str = "en") -> None:
        self._lang = lang
        self._lines: list[str] = []
        self._tr: dict[str, str] = I18N.get(lang, I18N["en"])

    # ------------------------------------------------------------------
    # i18n
    # ------------------------------------------------------------------

    @property
    def lang(self) -> str:
        """Current language code."""
        return self._lang

    def t(self, key: str, default: str | None = None) -> str:
        """Look up a translated string.

        Args:
            key: Translation key.
            default: Fallback if key is missing (default: ``key`` itself).

        Returns:
            Translated string.
        """
        return self._tr.get(key, default if default is not None else key)

    # ------------------------------------------------------------------
    # Raw content
    # ------------------------------------------------------------------

    def raw(self, text: str) -> MdReportBuilder:
        """Append arbitrary raw text as a single line."""
        if "\n" in text:
            self._lines.extend(text.split("\n"))
        else:
            self._lines.append(text)
        return self

    def blank(self) -> MdReportBuilder:
        """Add a blank line."""
        if self._lines and self._lines[-1] != "":
            self._lines.append("")
        return self

    # ------------------------------------------------------------------
    # Headers
    # ------------------------------------------------------------------

    def h(self, level: int, text: str) -> MdReportBuilder:
        """Add a heading of *level* (1\u20136)."""
        self._lines.append(f"{'#' * level} {text}")
        self._lines.append("")
        return self

    def h1(self, text: str) -> MdReportBuilder:
        """Level-1 heading."""
        return self.h(1, text)

    def h2(self, text: str) -> MdReportBuilder:
        """Level-2 heading."""
        return self.h(2, text)

    def h3(self, text: str) -> MdReportBuilder:
        """Level-3 heading."""
        return self.h(3, text)

    def h4(self, text: str) -> MdReportBuilder:
        """Level-4 heading."""
        return self.h(4, text)

    def h5(self, text: str) -> MdReportBuilder:
        """Level-5 heading."""
        return self.h(5, text)

    def h6(self, text: str) -> MdReportBuilder:
        """Level-6 heading."""
        return self.h(6, text)

    # ------------------------------------------------------------------
    # Paragraphs and text
    # ------------------------------------------------------------------

    def p(self, text: str) -> MdReportBuilder:
        """Add a paragraph of text."""
        self._lines.append(text)
        self._lines.append("")
        return self

    def hr(self) -> MdReportBuilder:
        """Add a horizontal rule (``---``)."""
        self._lines.append("---")
        self._lines.append("")
        return self

    def br(self) -> MdReportBuilder:
        """Add a line break tag (``<br>``)."""
        self._lines.append("<br>")
        self._lines.append("")
        return self

    def blockquote(self, text: str) -> MdReportBuilder:
        """Add a blockquote, wrapping long lines at 80 chars."""
        for line in text.split("\n"):
            self._lines.append(f"> {line}")
        self._lines.append("")
        return self

    def bullet_list(self, items: list[str]) -> MdReportBuilder:
        """Add an unordered list."""
        for item in items:
            self._lines.append(f"- {item}")
        self._lines.append("")
        return self

    def numbered_list(self, items: list[str]) -> MdReportBuilder:
        """Add an ordered list."""
        for i, item in enumerate(items, 1):
            self._lines.append(f"{i}. {item}")
        self._lines.append("")
        return self

    # ------------------------------------------------------------------
    # Inline formatting helpers (return strings)
    # ------------------------------------------------------------------

    @staticmethod
    def bold(text: str) -> str:
        """Wrap text in bold markers."""
        return f"**{text}**"

    @staticmethod
    def italic(text: str) -> str:
        """Wrap text in italic markers."""
        return f"*{text}*"

    @staticmethod
    def code(text: str) -> str:
        """Wrap text in inline code backticks."""
        return f"``{text}``"

    @staticmethod
    def link(text: str, url: str) -> str:
        """Generate a Markdown link."""
        return f"[{text}]({url})"

    @staticmethod
    def image(alt: str, url: str, title: str | None = None) -> str:
        """Generate a Markdown image reference."""
        suffix = f' "{title}"' if title else ""
        return f"![{alt}]({url}{suffix})"

    # ------------------------------------------------------------------
    # Tables
    # ------------------------------------------------------------------

    def table(
        self,
        headers: list[str],
        rows: list[list[str]],
        align: str | None = None,
    ) -> MdReportBuilder:
        """Add a Markdown table.

        Args:
            headers: Column header labels.
            rows: Data rows (each must match headers length).
            align: ``"left"``, ``"center"``, or ``"right"`` (default: ``"left"``).
        """
        col_count = len(headers)
        sep = _align_separator(col_count, align)
        self._lines.append(f"| {' | '.join(headers)} |")
        self._lines.append(f"|{sep}|")
        for row in rows:
            # Pad shorter rows
            padded = list(row) + [""] * (col_count - len(row))
            self._lines.append(f"| {' | '.join(padded)} |")
        self._lines.append("")
        return self

    # ------------------------------------------------------------------
    # Code blocks
    # ------------------------------------------------------------------

    def code_block(self, code: str, lang: str = "") -> MdReportBuilder:
        """Add a fenced code block.

        Args:
            code: The code content.
            lang: Optional language identifier (e.g. ``"python"``, ``"json"``).
        """
        self._lines.append(f"```{lang}")
        self._lines.append(code)
        self._lines.append("```")
        self._lines.append("")
        return self

    # ------------------------------------------------------------------
    # Mermaid helpers
    # ------------------------------------------------------------------

    def mermaid(self, body: str) -> MdReportBuilder:
        """Add a generic Mermaid diagram (wrapped in a fenced code block).

        Args:
            body: The Mermaid diagram body (everything after the `````mermaid`` line).
        """
        self._lines.append("```mermaid")
        self._lines.append(body)
        self._lines.append("```")
        self._lines.append("")
        return self

    def mermaid_bar(
        self,
        title: str,
        labels: list[str],
        values: list[float],
        *,
        y_label: str = "Score (1-5)",
        y_min: int = 0,
        y_max: int = 5,
    ) -> MdReportBuilder:
        """Add a vertical bar chart via Mermaid ``xychart``.

        Per the official docs (https://mermaid.js.org/syntax/xyChart.html)::

            xychart
                title "Title"
                x-axis ["A", "B", "C"]
                y-axis "Score (1-5)" 0 --> 5
                bar [4.5, 3.0, 5.0]

        Args:
            title: Chart title.
            labels: Category labels for the x-axis.
            values: Numeric bar heights.
            y_label: Y-axis label.
            y_min: Y-axis minimum.
            y_max: Y-axis maximum.
        """
        quoted = ", ".join(f'"{l}"' for l in labels)
        vals = ", ".join(f"{v:.2f}" for v in values)
        body = (
            f"xychart\n"
            f'    title "{title}"\n'
            f"    x-axis [{quoted}]\n"
            f'    y-axis "{y_label}" {y_min} --> {y_max}\n'
            f"    bar [{vals}]"
        )
        return self.mermaid(body)

    def mermaid_pie(self, title: str, data: dict[str, float]) -> MdReportBuilder:
        """Add a Mermaid pie chart.

        Args:
            title: Chart title.
            data: Mapping of slice labels to values.
        """
        body_lines = [f"pie title {title}"]
        for label, val in data.items():
            body_lines.append(f'    "{label}" : {val}')
        return self.mermaid("\n".join(body_lines))

    def mermaid_flowchart(
        self, direction: str, nodes: list[str], edges: list[tuple[str, str, str]]
    ) -> MdReportBuilder:
        """Add a Mermaid flowchart.

        Args:
            direction: ``"LR"`` (left\u2192right) or ``"TD"`` (top\u2192down).
            nodes: Node declarations, e.g. ``["A[Start]", "B[End]"]``.
            edges: ``(from_id, to_id, label)`` tuples.
        """
        body_lines = [f"flowchart {direction}"]
        for node in nodes:
            body_lines.append(f"    {node}")
        for src, tgt, label in edges:
            body_lines.append(f"    {src} -->|{label}| {tgt}")
        return self.mermaid("\n".join(body_lines))

    # ------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------

    def meta(self, key: str, value: str) -> MdReportBuilder:
        """Add a metadata line in ``**Key:** value`` format.

        Example::

            builder.meta("Generated", "2025-07-25 13:00")  # → **Generated:** 2025-07-25 13:00
        """
        self._lines.append(f"**{key}:** {value}")
        return self

    def meta_block(self, pairs: dict[str, str]) -> MdReportBuilder:
        """Add a block of metadata lines."""
        for key, value in pairs.items():
            self._lines.append(f"**{key}:** {value}")
        self._lines.append("")
        return self

    # ------------------------------------------------------------------
    # Figure caption
    # ------------------------------------------------------------------

    def figure_caption(
        self, number: int, description: str, lang: str | None = None
    ) -> MdReportBuilder:
        """Add an italicised figure caption.

        Args:
            number: Figure number.
            description: Caption text.
            lang: Language for the word "Figure" (default: instance language).
        """
        tr = I18N.get(lang or self._lang, self._tr)
        prefix = tr.get("figure_prefix", "Figure")
        return self.p(f"*{prefix} {number}: {description}.*")

    # ------------------------------------------------------------------
    # Build
    # ------------------------------------------------------------------

    def build(self) -> str:
        """Assemble the document into a single Markdown string.

        Trailing blank lines are stripped for cleanliness.
        """
        text = "\n".join(self._lines)
        # Strip trailing whitespace lines
        text = text.rstrip("\n") + "\n"
        return text

    def reset(self) -> MdReportBuilder:
        """Clear all accumulated content (reuse the builder)."""
        self._lines.clear()
        return self

    # ------------------------------------------------------------------
    # Length / preview
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        """Number of lines currently accumulated."""
        return len(self._lines)

    def __str__(self) -> str:
        """Same as :meth:`build`."""
        return self.build()


# ======================================================================
# Internal helpers
# ======================================================================


def _align_separator(col_count: int, align: str | None) -> str:
    """Generate the Markdown table alignment separator line."""
    parts: list[str] = []
    for _ in range(col_count):
        if align == "center":
            parts.append(":---:")
        elif align == "right":
            parts.append("---:")
        else:
            parts.append("---")
    return "|".join(parts)
